### PR TITLE
RF-12605: Fix Autocomplete Component Javascript Errors

### PR DESCRIPTION
**Pull request by mortenlud**
RF-12605: Fix Autocomplete Component Javascript Errors

### CODE REVIEW

**Comment by lfryc** [comment]
Thanks for a patch, Morten!

I start to think we will need to cover this functionality by functional tests.

Feel free to Link a pull request to specific JIRA issue next time [1]

[1] https://community.jboss.org/wiki/GuideToUsePullRequestsWithGitHubAndJIRA

**Comment by lfryc** [comment]
Hey Morten, I'm getting back to this pull request, I found it is not solving RF-12605 completely.

I have solved issue with AJAX re-rendering (switching tabs), and now I'm going to apply your fix.

However I think the fix is not completely right, because after re-redering autocomplete, the suggestion list could actually not be closed (it should just be replaced with another one). WDYT?

**Comment by lfryc** [comment]
Hey Morten, thanks for pull requests.

Finally I have dived into an issue and created a test and come with following fix:

https://github.com/richfaces/components/commit/99187a383682cc95766334de2627cb018a986746

Would be great if you can re-test issue in your app.

**Comment by lfryc** [comment]
Closing pull request since it was fixed in 99187a3

**Comment by mortenlud** [comment]
Thanks!

The solution looks nice. I will test it on my app on Monday.

Mvh
Morten L

**Comment by lfryc** [comment]
Awesome, thanks, let me please know if you will have any problem with that.

**Pull request closed without merging**
