### PR TITLE
Update AutocompleteBase.js

### PR DESCRIPTION
**Pull request by mimmazzo**
RF-12812 - Autocomplete does not hide popup on tabbing to the next field

### CODE REVIEW

**Comment by bleathem** [comment]
Excellent @mimmazzo thanks for the contribution.  Have you signed the CLA?

https://cla.jboss.org

We need you to do that before we can merge this patch.  Thanks!

**Comment by mimmazzo** [comment]
CLA signed.

**Comment by bleathem** [comment]
CLA signing confirmed and approved.  Thanks!

**Comment by lfryc** [comment]
Merged to the `master`: https://github.com/richfaces/components/commit/a05122f6f227be7226fb1eb17863409c85b8845f

Thanks @mimmazzo

**Pull request closed without merging**
