### PR TITLE
RF-12236: Fixing breaking scroll while resizing.

### PR DESCRIPTION
**Pull request by mwojciechowski**
I fixed bug RF-12236. The description of the solution is in comment to JIRA issue. (https://issues.jboss.org/browse/RF-12236). Additionally I corrected scrolling position after resizing column.

### CODE REVIEW

**Comment by lfryc** [comment]
Hey Michal,

cool, thanks for fixing this issue an providing pull request to upstream!

Could you please make sure to sign Contributor License Agreement for RichFaces?

https://cla.jboss.org/index.seam

Cheers,

~ Lukas

**Comment by mwojciechowski** [comment]
Hey Lukas,

I already did on September 3rd when I was forking the repository (according
to contributor guide instruction on wiki -
https://community.jboss.org/wiki/ContributorGettingStartedGuide) but it's
still awaiting for approval.

Cheers,

Micha³

2012/9/10 Lukas Fryc notifications@github.com

**Comment by lfryc** [comment]
Okay, I will make sure it is accepted as soon as possible.

Just note we are currently undergoing re-structure of the RichFaces build
and I will merge your pull request once it is finished [1].

The new repository is baked here:
https://github.com/richfaces/richfaces

[1] https://issues.jboss.org/browse/RF-12477

**Comment by lfryc** [comment]
Okay, we have postponed build updates,

so I have merged your pull request to `develop` of `components` branch.

Thanks for your efforts, Michał!

**Pull request closed without merging**
