### PR TITLE
added missing classes to deployment in test for rich:focus

### PR DESCRIPTION
**Pull request by ppitonak**

### CODE REVIEW

**Comment by lfryc** [comment]
I believe this is fixed now: https://github.com/richfaces/richfaces5/blob/6a0d8bed35378e4f6acde974751b3f46fff0ff1e/framework/src/test/integration/org/richfaces/component/focus/TestFocusDefaults.java#L43

**Comment by ppitonak** [comment]
That fix is for RichFaces 5, does it mean that you are not going to fix it in RichFaces 4?

**Comment by lfryc** [comment]
Good point.

**Comment by lfryc** [comment]
This bug is already fixed in RichFaces 4 as well:
https://github.com/richfaces/components/blob/develop/misc/ui/src/test/integration/org/richfaces/component/focus/TestFocusDefaults.java#L43

**Pull request closed without merging**
