### PR TITLE
Changed access level for inner classes/enums of class 'org.richfaces.renderkit.ExtendedDataTableRenderer'

### PR DESCRIPTION
**Pull request by rchigvintsev**
Fixing an issue RF-13453

### CODE REVIEW

**Comment by lfryc** [comment]
I feel that also other attributes could be used in protected mode for extending EDT: e.g. `getOrderedColumns`. 

We could also mark `class Part` as `final` (as it's not intended to be extended).

Otherwise your pull request seems fine.
We might expose other members as necessary for extensions as we go.

**Comment by lfryc** [comment]
@positiveCoder could you please sign CLA as described here?
https://github.com/richfaces/richfaces/blob/master/CONTRIBUTING.md

**Comment by rchigvintsev** [comment]
@lfryc Thank you for the advice. I've pushed another commit with suggested changes.
P.S. And I've signed CLA.

**Comment by lfryc** [comment]
Thanks @positiveCoder I have merged your patch to `master`.

**Pull request merged**
