### PR TITLE
RF-12457 Add onvalid and oninvalid to rich:validator

### PR DESCRIPTION
**Pull request by blabno**
onvalid and oninvalid are executed both on ajax fallback and on pure csv

### CODE REVIEW

**Comment by lfryc** [comment]
Hey Bernard,

thanks for the pull request.

Could you please take a look why Validator tests failed?

https://buildhive.cloudbees.com/job/richfaces/job/components/43/org.richfaces.ui.validator$richfaces-ui-validator-ui/console

```
Failed tests:   testCreateValidatorScriptPartialValidator(org.richfaces.renderkit.html.RendererGetComponentScriptTest): (..)
  testCreateValidatorScriptNullConverter(org.richfaces.renderkit.html.RendererGetComponentScriptTest): (..)
  testCreateValidatorScriptClientOnly(org.richfaces.renderkit.html.RendererGetComponentScriptTest): (..)

Tests run: 167, Failures: 3, Errors: 0, Skipped: 4

[ERROR] There are test failures.
```

**Comment by blabno** [comment]
Lukas, behavior mock didn't expect calls to getOnvalid/getOninvalid. I've fixed that.

**Comment by lfryc** [comment]
Cool, thanks Bernard!

As I said, I will merge this one to the new project structure which is conceiveing here:
https://github.com/richfaces/richfaces

**Comment by lfryc** [comment]
Thanks Bernard,

I have pushed this great addition to `develop`.

~ Lukas

**Pull request closed without merging**
