### PR TITLE
RF-11776 Add columnsOrder attribute to AbstractExtendedDataTable

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by lfryc** [comment]
Heya, thanks for the pull request!

Could you please make sure to sign Contributor License Agreement [1] for RichFaces project?

[1] https://cla.jboss.org/index.seam

**Comment by bleathem** [comment]
A CLA for Kent Vogel was signed, identifying this fix as the reason for signing.  

@f7sharp11 - you are Kent Vogel, correct?

Thanks for the pull request!

**Comment by ghost** [comment]
Yes, that is my github id.

**Comment by lfryc** [comment]
Merged to `develop`, Thanks Kent!

**Pull request closed without merging**
